name: Generate Registry Files

on:
  workflow_dispatch:

jobs:
  generate-registry-files:
    runs-on: ubuntu-latest

    steps:
      - name: Clone AtlasReg Repository
        run: |
          git clone https://github.com/SegoCode/AtlasReg.git

      - name: Clone Atlas Repository
        run: |
          git clone https://github.com/Atlas-OS/Atlas.git

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd AtlasReg/code
          npm ci

      - name: Run reg.js Script
        run: |
          cd AtlasReg/code
          node reg.js ../../Atlas/src/playbook ../playbook

      - name: Commit and Push Changes
        run: |
          cd AtlasReg
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playbook
          git commit -m "Update registry files"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SegoCode/AtlasReg.git
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
